import React, { createContext, useContext, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import './styles.css';

type Lang = 'ru' | 'ky';
type OrderStatus = 'новая' | 'в обработке' | 'подтверждена' | 'отменена';
type Product = { id: number; name: string; category: string; country: string; price: number; minOrder: number; image: string; popular?: boolean; available: string; description: string; specs: Record<string, string> };
type CartItem = { product: Product; qty: number };
type RequestForm = { name: string; phone: string; company: string; city: string; comment: string };
type ClientRequest = RequestForm & { id: number; status: OrderStatus; total: number; items: CartItem[] };

const categories = ['курага', 'изюм', 'чернослив', 'финики', 'инжир', 'орехи', 'смеси сухофруктов'];
const productsSeed: Product[] = [
  { id: 1, name: 'Курага Экстра', category: 'курага', country: 'Кыргызстан', price: 310, minOrder: 25, image: 'https://images.unsplash.com/photo-1596525903404-5805ae63049a?auto=format&fit=crop&w=900&q=80', popular: true, available: 'В наличии', description: 'Мясистая сладкая курага для HoReCa, магазинов и переработчиков.', specs: { вес: '25 кг', сорт: 'Экстра', упаковка: 'гофрокороб', страна: 'Кыргызстан', 'срок хранения': '12 месяцев', 'условия хранения': '+5…+20°C, сухое место' } },
  { id: 2, name: 'Изюм золотой', category: 'изюм', country: 'Узбекистан', price: 185, minOrder: 50, image: 'https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?auto=format&fit=crop&w=900&q=80', popular: true, available: 'В наличии', description: 'Светлый изюм без косточки с ровной фракцией и натуральной сладостью.', specs: { вес: '10 кг', сорт: 'Голден', упаковка: 'мешок', страна: 'Узбекистан', 'срок хранения': '10 месяцев', 'условия хранения': 'до +18°C' } },
  { id: 3, name: 'Чернослив без косточки', category: 'чернослив', country: 'Таджикистан', price: 260, minOrder: 25, image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80', available: 'В наличии', description: 'Мягкий чернослив калиброванный, подходит для фасовки и кондитерского производства.', specs: { вес: '20 кг', сорт: 'Премиум', упаковка: 'короб', страна: 'Таджикистан', 'срок хранения': '9 месяцев', 'условия хранения': '+2…+15°C' } },
  { id: 4, name: 'Финики Deglet Nour', category: 'финики', country: 'Тунис', price: 220, minOrder: 30, image: 'https://images.unsplash.com/photo-1601379760883-1bb497c55851?auto=format&fit=crop&w=900&q=80', popular: true, available: 'Склад Бишкек', description: 'Полусухие финики на ветке с карамельным вкусом.', specs: { вес: '5 кг', сорт: 'Deglet Nour', упаковка: 'лоток/короб', страна: 'Тунис', 'срок хранения': '12 месяцев', 'условия хранения': 'прохладное сухое место' } },
  { id: 5, name: 'Инжир натуральный', category: 'инжир', country: 'Турция', price: 340, minOrder: 20, image: 'https://images.unsplash.com/photo-1609595809161-fd3c3d572111?auto=format&fit=crop&w=900&q=80', available: 'Под заказ', description: 'Сушёный инжир крупного калибра для премиальной розницы.', specs: { вес: '10 кг', сорт: 'Lerida', упаковка: 'короб', страна: 'Турция', 'срок хранения': '8 месяцев', 'условия хранения': '+5…+15°C' } },
  { id: 6, name: 'Ореховый микс', category: 'орехи', country: 'Кыргызстан', price: 520, minOrder: 15, image: 'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=900&q=80', available: 'В наличии', description: 'Смесь миндаля, грецкого ореха и кешью для магазинов здорового питания.', specs: { вес: '10 кг', сорт: 'Ассорти', упаковка: 'вакуумный пакет', страна: 'Кыргызстан', 'срок хранения': '6 месяцев', 'условия хранения': 'до +15°C' } },
  { id: 7, name: 'Компотная смесь', category: 'смеси сухофруктов', country: 'Кыргызстан', price: 145, minOrder: 100, image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80', available: 'В наличии', description: 'Оптовая смесь яблока, урюка, груши и изюма для напитков и столовых.', specs: { вес: '25 кг', сорт: 'Стандарт', упаковка: 'мешок', страна: 'Кыргызстан', 'срок хранения': '12 месяцев', 'условия хранения': 'сухой склад' } },
];

const tr = { ru: { catalog: 'Каталог', request: 'Заявка', admin: 'Админ', hero: 'Оптовая продажа сухофруктов', cta: 'Смотреть каталог' }, ky: { catalog: 'Каталог', request: 'Буйрутма', admin: 'Админ', hero: 'Кургатылган жемиштерди дүң сатуу', cta: 'Каталогду көрүү' } };
const AppContext = createContext<any>(null);
const useApp = () => useContext(AppContext);

function Provider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('ru');
  const [dark, setDark] = useState(false);
  const [products, setProducts] = useState(productsSeed);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [requests, setRequests] = useState<ClientRequest[]>([{ id: 1001, name: 'Айбек', phone: '+996 555 111 222', company: 'Market KG', city: 'Бишкек', comment: 'Нужен прайс на изюм', status: 'новая', total: 9250, items: [{ product: productsSeed[1], qty: 50 }] }]);
  const addToCart = (product: Product) => setCart((items) => items.some((i) => i.product.id === product.id) ? items : [...items, { product, qty: product.minOrder }]);
  const value = { lang, setLang, t: tr[lang], dark, setDark, products, setProducts, cart, setCart, requests, setRequests, addToCart };
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

function Layout() { const { t, lang, setLang, dark, setDark, cart } = useApp(); return <div className={dark ? 'app dark' : 'app'}><header><Link className="logo" to="/">Fruit<span>Opt</span></Link><nav><NavLink to="/catalog">{t.catalog}</NavLink><NavLink to="/wholesale">Опт</NavLink><NavLink to="/delivery">Доставка</NavLink><NavLink to="/about">О компании</NavLink><NavLink to="/contacts">Контакты</NavLink><NavLink to="/cart">{t.request} ({cart.length})</NavLink><NavLink to="/admin">{t.admin}</NavLink></nav><div className="tools"><button onClick={() => setLang(lang === 'ru' ? 'ky' : 'ru')}>{lang.toUpperCase()}</button><button onClick={() => setDark(!dark)}>{dark ? '☀️' : '🌙'}</button></div></header><main><Routes><Route path="/" element={<Home />} /><Route path="/catalog" element={<Catalog />} /><Route path="/product/:id" element={<ProductPage />} /><Route path="/cart" element={<Cart />} /><Route path="/about" element={<Info title="О компании" text="Мы поставляем сухофрукты и орехи оптом для магазинов, кафе, производств и дистрибьюторов. Работаем с проверенными фермерскими хозяйствами и контролируем качество каждой партии." />} /><Route path="/wholesale" element={<Info title="Условия оптовой продажи" text="Минимальный заказ зависит от товара. Для постоянных клиентов действуют индивидуальные цены, резерв партий и регулярные поставки по графику." />} /><Route path="/delivery" element={<Info title="Доставка и оплата" text="Доставляем по Бишкеку и регионам транспортными компаниями. Оплата по счёту, наличным или переводом после подтверждения заявки менеджером." />} /><Route path="/contacts" element={<Contacts />} /><Route path="/admin" element={<Admin />} /></Routes></main><div className="messengers"><a href="https://wa.me/996555000000">WhatsApp</a><a href="https://t.me/fruitopt">Telegram</a></div><footer>© 2026 FruitOpt · Оптовые сухофрукты</footer></div> }
function Home() { const { products, t, addToCart } = useApp(); return <><section className="hero"><div><p className="eyebrow">FruitOpt Wholesale</p><h1>{t.hero}</h1><p>Качественные сухофрукты, орехи и смеси с прозрачными ценами и быстрой заявкой.</p><Link className="primary" to="/catalog">{t.cta}</Link></div></section><section><h2>Популярные товары</h2><div className="grid">{products.filter((p: Product) => p.popular).map((p: Product) => <Card key={p.id} product={p} onAdd={() => addToCart(p)} />)}</div></section><section className="advantages"><h2>Преимущества</h2><div><b>Оптовые цены</b><b>Сертифицированные партии</b><b>Доставка по регионам</b><b>Персональный менеджер</b></div></section><QuickForm /></> }
function Catalog() { const { products, addToCart } = useApp(); const [q, setQ] = useState(''); const [cat, setCat] = useState(''); const [sort, setSort] = useState(''); const list = useMemo(() => products.filter((p: Product) => (!cat || p.category === cat) && p.name.toLowerCase().includes(q.toLowerCase())).sort((a: Product,b: Product)=> sort === 'asc' ? a.price-b.price : sort === 'desc' ? b.price-a.price : 0), [products,q,cat,sort]); return <section><h1>Каталог товаров</h1><div className="filters"><input placeholder="Поиск товаров" value={q} onChange={e=>setQ(e.target.value)} /><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">Все категории</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="">Без сортировки</option><option value="asc">Цена ↑</option><option value="desc">Цена ↓</option></select></div><div className="grid">{list.map((p: Product)=><Card key={p.id} product={p} onAdd={()=>addToCart(p)} />)}</div></section> }
function Card({ product, onAdd }: { product: Product; onAdd: () => void }) { return <article className="card"><img src={product.image} alt={product.name}/><div><small>{product.category} · {product.country}</small><h3><Link to={`/product/${product.id}`}>{product.name}</Link></h3><p>{product.price} сом/кг · мин. {product.minOrder} кг</p><button onClick={onAdd}>Добавить в заявку</button></div></article> }
function ProductPage() { const { id } = useParams(); const { products, addToCart } = useApp(); const p = products.find((x: Product)=> x.id === Number(id)) || products[0]; return <section className="product"><img src={p.image} alt={p.name}/><div><h1>{p.name}</h1><p>{p.description}</p><h2>{p.price} сом за 1 кг</h2><p>Минимальный заказ: {p.minOrder} кг · Наличие: {p.available}</p><dl>{Object.entries(p.specs).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{String(v)}</dd></React.Fragment>)}</dl><button onClick={()=>addToCart(p)}>Добавить в заявку</button></div></section> }
function Cart() { const { cart, setCart, setRequests } = useApp(); const { register, handleSubmit, reset, formState:{errors} } = useForm<RequestForm>(); const total = cart.reduce((s: number, i: CartItem)=>s+i.qty*i.product.price,0); const submit=(data: RequestForm)=>{ setRequests((r: ClientRequest[])=>[{...data,id:Date.now(),status:'новая',total,items:cart},...r]); setCart([]); reset(); alert('Заявка отправлена'); }; return <section><h1>Корзина / заявка</h1>{cart.map((i: CartItem)=><div className="cart" key={i.product.id}><b>{i.product.name}</b><input type="number" min={i.product.minOrder} value={i.qty} onChange={e=>setCart(cart.map((x: CartItem)=>x.product.id===i.product.id?{...x,qty:+e.target.value}:x))}/><span>{i.qty*i.product.price} сом</span><button onClick={()=>setCart(cart.filter((x: CartItem)=>x.product.id!==i.product.id))}>Удалить</button></div>)}<h2>Примерная сумма: {total} сом</h2><form onSubmit={handleSubmit(submit)} className="form"><input placeholder="Имя" {...register('name',{required:true})}/><input placeholder="Телефон" {...register('phone',{required:true,minLength:6})}/><input placeholder="Компания" {...register('company')}/><input placeholder="Город" {...register('city',{required:true})}/><textarea placeholder="Комментарий" {...register('comment')}/><button>Отправить заявку</button>{Object.keys(errors).length>0 && <p className="error">Проверьте обязательные поля</p>}</form></section> }
function QuickForm(){ const { register, handleSubmit, reset } = useForm<RequestForm>(); return <section><h2>Быстрая заявка</h2><form className="form small" onSubmit={handleSubmit(()=>{alert('Менеджер свяжется с вами'); reset();})}><input placeholder="Имя" {...register('name',{required:true})}/><input placeholder="Телефон" {...register('phone',{required:true})}/><button>Отправить</button></form></section> }
function Admin(){ const { products,setProducts,requests,setRequests }=useApp(); const [auth,setAuth]=useState(false); const { register, handleSubmit, reset }=useForm<any>(); if(!auth)return <section className="login"><h1>Вход в админ-панель</h1><input placeholder="Логин"/><input placeholder="Пароль" type="password"/><button onClick={()=>setAuth(true)}>Войти</button><small>Демо-доступ для администратора</small></section>; return <section><h1>Админ-панель</h1><h2>Товары</h2><form className="form small" onSubmit={handleSubmit(d=>{setProducts([...products,{...d,id:Date.now(),price:+d.price,minOrder:+d.minOrder,image:d.image||productsSeed[0].image,available:'В наличии',description:d.description||'Описание товара',specs:productsSeed[0].specs}]);reset();})}><input placeholder="Название" {...register('name',{required:true})}/><select {...register('category')}>{categories.map(c=><option key={c}>{c}</option>)}</select><input placeholder="Страна" {...register('country')}/><input placeholder="Цена" type="number" {...register('price')}/><input placeholder="Мин. заказ" type="number" {...register('minOrder')}/><input placeholder="Фото URL" {...register('image')}/><button>Добавить товар</button></form>{products.map((p: Product)=><div className="admin-row" key={p.id}><span>{p.name} — {p.price} сом</span><button onClick={()=>setProducts(products.map((x: Product)=>x.id===p.id?{...x,price:x.price+10}:x))}>+10 к цене</button><button onClick={()=>setProducts(products.filter((x: Product)=>x.id!==p.id))}>Удалить</button></div>)}<h2>Заявки клиентов</h2>{requests.map((r: ClientRequest)=><div className="admin-row" key={r.id}><span>#{r.id} {r.name}, {r.city}, {r.total} сом — {r.status}</span><select value={r.status} onChange={e=>setRequests(requests.map((x: ClientRequest)=>x.id===r.id?{...x,status:e.target.value as OrderStatus}:x))}>{['новая','в обработке','подтверждена','отменена'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section> }
function Info({title,text}:{title:string;text:string}){ return <section className="page"><h1>{title}</h1><p>{text}</p></section> }
function Contacts(){ return <section className="page"><h1>Контакты</h1><p>Бишкек, ул. Складская 12 · +996 555 000 000 · sales@fruitopt.kg</p><p>Пишите в WhatsApp или Telegram — менеджер подготовит коммерческое предложение.</p></section> }
function App(){ return <Provider><BrowserRouter><Layout /></BrowserRouter></Provider> }

createRoot(document.getElementById('root')!).render(<App />);
